### ISSUE TITLE
.envに設定する環境変数

### ISSUE THREAD

**Issue by atarubift** [webfrontier/hr-dash#2]
# 概要
README内に設定すると書かれているが具体的に何が必要なのかがわからない。
ソースコード内から以下の環境変数を設定する必要があることがわかった。

- ENCRYPTOR_CIPHER
- ENCRYPTOR_SALT
- ENCRYPTOR_PASS

他にもあるか調査が必要。
# 再現・確認手順（任意）

# ToDo

- [ ] 各環境変数に設定る値
- [ ] ほかにもあるか調査

**Comment by atarubift** [comment]
暗号化についていろいろ調べた
ENCRYPTOR_CIPHER は変換の方式
ENCRYPTOR_SALT は8byteのsalt文字列
ENCRYPTOR_PASS はpasswordが入りそう

**Comment by KazuyukiSomeya** [comment]
@atarubift 
環境変数のリストをもらいました。
メール環境はいま準備できるものがないので、可能であればモックにできたらと思いますがどうでしょうか？

BASIC_AUTH_USERNAME=admin
BASIC_AUTH_PASSWORD=pass
ENCRYPTOR_CIPHER=AES-256-CBC
ENCRYPTOR_PASS=password
ENCRYPTOR_SALT=個々の環境で設定
MAILER_ADDRESS=smtp.gmail.com
MAILER_PORT=ポート
MAILER_DOMAIN=ドメイン
MAILER_USERNAME=ユーザ名
MAILER_PASSWORD=パスワード
MAILER_FROM=適当なメールアドレス
MAILER_DEFAULT_HOST=localhost:3000
SYSTEM_MAIL=メールアドレス
